name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    permissions: 
      contents: add
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Gen font page
        run: |
          cat > dist/README.md <<EOL
          # ***I'm Carlos Yazid Padilla***! 📈🇨🇴
          ![Banner-1.png](https://i.postimg.cc/sg8pqvcH/Banner-1.png)
          ![Visitors](https://api.visitorbadge.io/api/combined?path=https%3A%2F%2Fgithub.com%2FCarlosYazid&label=Visitors&labelColor=%23ba68c8&countColor=%232ccce4&style=flat)
          ---
          
          - 👀 I’m interested in Data
          - 🌱 I’m currently learning a little of everything
          - 📫 How to reach me ...
          - 😄 Pronouns: He
          
          ## 🌐*Socials*
          [![Discord](https://img.shields.io/badge/Discord-%237289DA.svg?logo=discord&logoColor=white)](https://discord.gg/939669249658601493) [![LinkedIn](https://img.shields.io/badge/LinkedIn-%230077B5.svg?logo=linkedin&logoColor=white)](https://linkedin.com/in/carlospadillar) [![Reddit](https://img.shields.io/badge/Reddit-%23FF4500.svg?logo=Reddit&logoColor=white)](https://reddit.com/user/Hawk7669Colombia) 
          
          # 💻*Tech Stack*
          
          *Data* | *Cloud* | *Others*
          |:---:|:---:|:---:
          | ![Python][Python] | ![AWS][AWS] | ![Markdown][Markdown]    	    
          | ![Anaconda][Anaconda] | ![Azure][Azure]  | ![Canva][Canva]
          | ![OpenCV][OpenCV] | ![Google Cloud][GoogleCloud] | ![Notion][Notion]
          | ![NumPy][NumPy] | ![Oracle][Oracle] | ![Jira][Jira] 
          | ![Pandas][Pandas] | ![Docker][Docker] | ![Spring][Spring]
          | ![PyTorch][PyTorch] | ![Shell Script][ShellScript] | ![Postman][Postman]
          | ![Plotly][Plotly] | ![Apache Airflow][ApacheAirflow] | ![Apache Maven][ApacheMaven]
          | ![TensorFlow][TensorFlow] | ![Kubernetes][Kubernetes] | ![GithubPages][GithubPages]
          | ![AmazonDynamoDB][AmazonDynamoDB] | ![GitHub Actions][GitHubActions] | ![Yarn][Yarn]
          | ![ApacheCassandra][ApacheCassandra] | ![GitHub][GitHub] | ![Hibernate][Hibernate]
          | ![MariaDB][MariaDB] | |
          | ![MicrosoftSQLServer][MicrosoftSQLServer] | |
          | ![MongoDB][MongoDB] | | 
          | ![MySQL][MySQL] | |
          | ![Postgres][Postgres] | |
          | ![ApacheHadoop][ApacheHadoop] | |
          | ![Apache Spark][ApacheSpark] | |
          | ![Java][Java] | |
          | ![Scala][Scala] | |
          | ![SQLite][SQLite] | |
          | ![Scipy][Scipy] | |
          | ![R][R] | |
          | ![Apache Kafka][ApacheKafka] | |
          | ![Apache Hadoop][ApacheHadoop] | |
          | ![Apache Hive][ApacheHive] | |
          | ![CockroachLabs][CockroachLabs] | |
          | ![Couchbase][Couchbase] | |
          | ![Redis][Redis] | |
          | ![mlflow][mlflow] | |
          | ![Matplotlib][Matplotlib] | |
          | ![Keras][Keras] | |
          | ![scikit-learn][scikit-learn] | |
          
          
          # 📊*GitHub Stats*
          ![](dist/github-contribution-grid-snake-dark.svg)<br/>
          ![](https://github-readme-stats.vercel.app/api/top-langs/?username=CarlosYazid&theme=radical&hide_border=false&include_all_commits=false&count_private=false&layout=compact)
          
          ## 🏆*GitHub Trophies*
          ![](https://github-trophies.vercel.app/?username=CarlosYazid&theme=radical&no-frame=true&no-bg=true&margin-w=4)
          
          <!--Data-->
          [Python]: https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54
          [Anaconda]: https://img.shields.io/badge/Anaconda-%2344A833.svg?style=for-the-badge&logo=anaconda&logoColor=white
          [OpenCV]: https://img.shields.io/badge/opencv-%23white.svg?style=for-the-badge&logo=opencv&logoColor=white
          [NumPy]: https://img.shields.io/badge/numpy-%23013243.svg?style=for-the-badge&logo=numpy&logoColor=white
          [Pandas]: https://img.shields.io/badge/pandas-%23150458.svg?style=for-the-badge&logo=pandas&logoColor=white
          [PyTorch]: https://img.shields.io/badge/PyTorch-%23EE4C2C.svg?style=for-the-badge&logo=PyTorch&logoColor=white
          [Plotly]: https://img.shields.io/badge/Plotly-%233F4F75.svg?style=for-the-badge&logo=plotly&logoColor=white
          [TensorFlow]: https://img.shields.io/badge/TensorFlow-%23FF6F00.svg?style=for-the-badge&logo=TensorFlow&logoColor=white
          [AmazonDynamoDB]: https://img.shields.io/badge/Amazon%20DynamoDB-4053D6?style=for-the-badge&logo=Amazon%20DynamoDB&logoColor=white
          [ApacheCassandra]: https://img.shields.io/badge/cassandra-%231287B1.svg?style=flat&logo=apache-cassandra&logoColor=white
          [MicrosoftSQLServer]: https://img.shields.io/badge/Microsoft%20SQL%20Sever-CC2927?style=flat&logo=microsoft%20sql%20server&logoColor=white
          [MongoDB]: https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=flat&logo=mongodb&logoColor=white
          [MySQL]: https://img.shields.io/badge/mysql-4479A1.svg?style=for-the-badge&logo=mysql&logoColor=white
          [Postgres]: https://img.shields.io/badge/postgres-%23316192.svg?style=for-the-badge&logo=postgresql&logoColor=white
          [SQLite]: https://img.shields.io/badge/sqlite-%2307405e.svg?style=for-the-badge&logo=sqlite&logoColor=white
          [Scipy]: https://img.shields.io/badge/SciPy-%230C55A5.svg?style=for-the-badge&logo=scipy&logoColor=%white
          [R]: https://img.shields.io/badge/r-%23276DC3.svg?style=for-the-badge&logo=r&logoColor=white
          [Java]: https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=openjdk&logoColor=white
          [ApacheHadoop]: https://img.shields.io/badge/Apache%20Hadoop-66CCFF?style=for-the-badge&logo=apachehadoop&logoColor=black
          [ApacheAirflow]: https://img.shields.io/badge/Apache%20Airflow-017CEE?style=for-the-badge&logo=Apache%20Airflow&logoColor=white
          [ApacheSpark]: https://img.shields.io/badge/Apache%20Spark-FDEE21?style=for-the-badge&logo=apachespark&logoColor=black
          [Scala]: https://img.shields.io/badge/scala-%23DC322F.svg?style=for-the-badge&logo=scala&logoColor=white
          [ApacheKafka]: https://img.shields.io/badge/Apache%20Kafka-000?style=for-the-badge&logo=apachekafka
          [ApacheHadoop]: https://img.shields.io/badge/Apache%20Hadoop-66CCFF?style=for-the-badge&logo=apachehadoop&logoColor=black
          [ApacheHive]: https://img.shields.io/badge/Apache%20Hive-FDEE21?style=for-the-badge&logo=apachehive&logoColor=black
          [CockroachLabs]: https://img.shields.io/badge/Cockroach%20Labs-6933FF?style=for-the-badge&logo=Cockroach%20Labs&logoColor=white
          [Couchbase]: https://img.shields.io/badge/Couchbase-EA2328?style=for-the-badge&logo=couchbase&logoColor=white
          [MariaDB]: https://img.shields.io/badge/MariaDB-003545?style=for-the-badge&logo=mariadb&logoColor=white
          [Redis]: https://img.shields.io/badge/redis-%23DD0031.svg?style=for-the-badge&logo=redis&logoColor=white
          [mlflow]: https://img.shields.io/badge/mlflow-%23d9ead3.svg?style=for-the-badge&logo=numpy&logoColor=blue
          [Matplotlib]: https://img.shields.io/badge/Matplotlib-%23ffffff.svg?style=for-the-badge&logo=Matplotlib&logoColor=black 
          [Keras]: https://img.shields.io/badge/Keras-%23D00000.svg?style=for-the-badge&logo=Keras&logoColor=white
          [scikit-learn]: https://img.shields.io/badge/scikit--learn-%23F7931E.svg?style=for-the-badge&logo=scikit-learn&logoColor=white
          
          <!--Cloud-->
          [AWS]: https://img.shields.io/badge/AWS-%23FF9900.svg?style=for-the-badge&logo=amazon-aws&logoColor=white
          [Azure]: https://img.shields.io/badge/azure-%230072C6.svg?style=for-the-badge&logo=microsoftazure&logoColor=white
          [GoogleCloud]: https://img.shields.io/badge/GoogleCloud-%234285F4.svg?style=for-the-badge&logo=google-cloud&logoColor=white 
          [Kubernetes]: https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white
          [Docker]: https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white
          [ShellScript]: https://img.shields.io/badge/shell_script-%23121011.svg?style=for-the-badge&logo=gnu-bash&logoColor=white
          [Oracle]: https://img.shields.io/badge/Oracle-F80000?style=for-the-badge&logo=oracle&logoColor=white
          [GitHubActions]: https://img.shields.io/badge/github%20actions-%232671E5.svg?style=for-the-badge&logo=githubactions&logoColor=white
          [GitHub]: https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white
          
          <!--Others-->
          [Markdown]: https://img.shields.io/badge/markdown-%23000000.svg?style=for-the-badge&logo=markdown&logoColor=white
          [Canva]: https://img.shields.io/badge/Canva-%2300C4CC.svg?style=for-the-badge&logo=Canva&logoColor=white
          [Figma]: https://img.shields.io/badge/figma-%23F24E1E.svg?style=flat&logo=figma&logoColor=white
          [Notion]: https://img.shields.io/badge/Notion-%23000000.svg?style=for-the-badge&logo=notion&logoColor=white
          [Jira]: https://img.shields.io/badge/jira-%230A0FFF.svg?style=for-the-badge&logo=jira&logoColor=white
          [Postman]: https://img.shields.io/badge/Postman-FF6C37?style=for-the-badge&logo=postman&logoColor=white
          [GithubPages]: https://img.shields.io/badge/github%20pages-121013?style=for-the-badge&logo=github&logoColor=white
          [Yarn]: https://img.shields.io/badge/yarn-%232C8EBB.svg?style=for-the-badge&logo=yarn&logoColor=white
          [Spring]: https://img.shields.io/badge/spring-%236DB33F.svg?style=for-the-badge&logo=spring&logoColor=white
          [ApacheMaven]: https://img.shields.io/badge/Apache%20Maven-C71A36?style=for-the-badge&logo=Apache%20Maven&logoColor=white
          [Hibernate]: https://img.shields.io/badge/Hibernate-59666C?style=for-the-badge&logo=Hibernate&logoColor=white
          
          ---
          [![](https://visitcount.itsvg.in/api?id=CarlosYazid&icon=0&color=0)](https://visitcount.itsvg.in)
          EOL>>
          
      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Add/update generated content"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
